print("Twinkle , Twinkle , little star,")
print("\t How I wonder what you are !")
print("\t \t Up Above the world so high,")
print("\t \t Like a diamond in the sky.")
print("Twinkle , Twinkle , little star,")
print("\t How I wonder what you are !")
