# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K6x2MzOcU9b1H8MSCA7whXFpepsSksnD
"""

n = input()
a = n.split(".")
print(a[1])

