# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K6x2MzOcU9b1H8MSCA7whXFpepsSksnD
"""

#Q7
n = input()
a = n.split(".")
print(a[1])
#already stores the result in the form of list

#Q8
colour_set = ["Red","Green","white","Block"]
print(colour_set[0])
print(colour_set[3])

#Q9
exam_st_date = (11,12,2014)
print(exam_st_date[0],"/",exam_st_date[1],"/",exam_st_date[2])
#We didnt use + as it won't accept concatenation of different data types

#Q11
n = int(input())
a = abs(n)
print("abs(n)= ",a)

#Q12
import calendar
#print(calendar.calendar(2018))
yy = 2001
mm = 10
print(calendar.month(yy,mm))

#Q13 Herodoc string or multiline string
print('''This
is a ....... multi-line
heredoc string --------''')

